#Purpose-----------------------------------------------------------------------------------------------------
# bcfishpass crossings_vw modelling table setup for reporting --------------------------
# **NOTE - 20240412 - THIS IS HYPOTHETICAL AS WE CURRENTLY DO NOT HAVE MOST THE COMMENTS INTHE DATABASE
# see https://github.com/NewGraphEnvironment/fish_passage_template_reporting/issues/1


#How this data can be made and updated-----------------------------------------------------------------------------------------------------
# connect to the database
conn <- fpr_db_conn()

bcfishpass <- fpr_db_query(
  "SELECT * from bcfishpass.crossings_vw LIMIT 1;"
  )

# comments_table should be `crossings_vw` but that has NO comments. crossings is incomplete but is example
comments_table <- "crossings"

bcfishpass_column_comments <- fpr_db_query(
  query <- glue::glue(
    "select col_description((table_schema||'.'||table_name)::regclass::oid, ordinal_position) as column_comment,
  * from information_schema.columns
  WHERE table_schema = 'bcfishpass'
  and table_name = '{comments_table}';"
  )
)

# When we need to update our column names according to the new output from bcfishpass.crossings...
bcfishpass_names_updated_prep <- names(bcfishpass) %>%
  tibble::as_tibble() %>%
  rename(bcfishpass = value)

# join to the comments
bcfishpass_names_updated <- left_join(
  bcfishpass_names_updated_prep,
  bcfishpass_column_comments,
  by = c('bcfishpass' = 'column_name')
)

#this is how we line up our new column names and put things in order for reporting on the fish habitat modeling
# we need to update this sometimes.  When we do we update 02_prep_reporting/0160-load-bcfishpass-data.R,
# get the data from  rename the xref_bcfishpass_names tribble to xref_bcfishpass_names_old  and go through the following procedure
xref_bcfishpass_names_old <- fpr_xref_crossings()


# ## join the new with the old so you can kable(xref_bcfishpass_names_prep) then run in Rmd chunk and copy paste tribble
xref_bcfishpass_names_prep <- left_join(
  bcfishpass_names_updated,
  xref_bcfishpass_names_old %>% select(-column_comment),
  by = c('bcfishpass')
) %>%
    mutate(report = stringr::str_replace_all(bcfishpass, '_', ' ') %>%
             stringr::str_to_title() %>%
             stringr::str_replace_all('Km', '(km)') %>%
             stringr::str_replace_all('Ha', '(ha)') %>%
             stringr::str_replace_all('Lakereservoir', 'Lake Reservoir') %>%
             stringr::str_replace_all('Co ', 'CO ') %>%
             stringr::str_replace_all('Ch', 'CH ') %>%
             stringr::str_replace_all('St ', 'ST ') %>%
             stringr::str_replace_all('Sk ', 'SK ') %>%
             stringr::str_replace_all('Bt ', 'BT ') %>%
             stringr::str_replace_all('Wct ', 'WCT ') %>%
             stringr::str_replace_all('Pscis', 'PSCIS') %>%
             stringr::str_replace_all('Spawningrearing', 'Spawning Rearing') %>%
             stringr::str_replace_all('Betweenbarriers', 'Between Barriers') %>%
             stringr::str_replace_all('Belowupstrbarriers', 'Below Barriers')) %>%
  select(bcfishpass, report, id_join, id_side, column_comment)


fpr_xref_crossings <- tibble::tribble(
                                                ~bcfishpass,                                                 ~report, ~id_join, ~id_side,                                                                                                                                                                                                                                          ~column_comment,
                                  "aggregated_crossings_id",                               "Aggregated Crossings Id",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                       "stream_crossing_id",                                    "Stream Crossing Id",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                                   "dam_id",                                                "Dam Id",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                            "user_barrier_anthropogenic_id",                         "User Barrier Anthropogenic Id",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                     "modelled_crossing_id",                                  "Modelled Crossing Id",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                          "crossing_source",                                       "Crossing Source",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                    "crossing_feature_type",                                 "Crossing Feature Type",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                             "pscis_status",                                          "PSCIS Status",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                       "crossing_type_code",                                    "Crossing Type Code",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                    "crossing_subtype_code",                                 "Crossing Subtype Code",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                            "modelled_crossing_type_source",                         "Modelled Crossing Type Source",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                           "barrier_status",                                        "Barrier Status",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                          "pscis_road_name",                                       "PSCIS Road Name",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                        "pscis_stream_name",                                     "PSCIS Stream Name",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                 "pscis_assessment_comment",                              "PSCIS Assessment Comment",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                    "pscis_assessment_date",                                 "PSCIS Assessment Date",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                        "pscis_final_score",                                     "PSCIS Final Score",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                         "transport_line_structured_name_1",                      "Transport Line Structured Name 1",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                          "transport_line_type_description",                       "Transport Line Type Description",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                       "transport_line_surface_description",                    "Transport Line Surface Description",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                      "ften_forest_file_id",                                   "Ften Forest File Id",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                               "ften_file_type_description",                            "Ften File Type Description",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                       "ften_client_number",                                    "Ften Client Number",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                         "ften_client_name",                                      "Ften Client Name",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                              "ften_life_cycle_status_code",                           "Ften Life Cycle Status Code",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                          "rail_track_name",                                       "Rail Track Name",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                          "rail_owner_name",                                       "Rail Owner Name",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                               "rail_operator_english_name",                            "Rail Operator English Name",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                            "ogc_proponent",                                         "Ogc Proponent",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                                 "dam_name",                                              "Dam Name",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                                "dam_owner",                                             "Dam Owner",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                                 "utm_zone",                                              "Utm Zone",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                              "utm_easting",                                           "Utm Easting",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                             "utm_northing",                                          "Utm Northing",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                         "dbm_mof_50k_grid",                                      "Dbm Mof 50k Grid",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                        "linear_feature_id",                                     "Linear Feature Id",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                            "blue_line_key",                                         "Blue Line Key",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                            "watershed_key",                                         "Watershed Key",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                 "downstream_route_measure",                              "Downstream Route Measure",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                             "wscode_ltree",                                          "Wscode Ltree",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                          "localcode_ltree",                                       "Localcode Ltree",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                     "watershed_group_code",                                  "Watershed Group Code",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                         "gnis_stream_name",                                      "Gnis Stream Name",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                             "stream_order",                                          "Stream Order",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                         "stream_magnitude",                                      "Stream Magnitude",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                        "observedspp_dnstr",                                     "Observedspp Dnstr",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                        "observedspp_upstr",                                     "Observedspp Upstr",       NA,       NA,                                                                                                                                                                                                                                                       NA,
                                          "crossings_dnstr",                                       "Crossings Dnstr",       NA,       NA,                                                                                                                                          "List of the aggregated_crossings_id values of crossings downstream of the given crossing, in order downstream",
                             "barriers_anthropogenic_dnstr",                          "Barriers Anthropogenic Dnstr",       NA,       NA,                                                                                                                                  "List of the aggregated_crossings_id values of barrier crossings downstream of the given crossing, in order downstream",
                             "barriers_anthropogenic_upstr",                          "Barriers Anthropogenic Upstr",       NA,       NA,                                                                                                                                                         "List of the aggregated_crossings_id values of barrier crossings upstream of the given crossing",
                       "barriers_anthropogenic_dnstr_count",                    "Barriers Anthropogenic Dnstr Count",       NA,       NA,                                                                                                                                                                                      "A count of the barrier crossings downstream of the given crossing",
                       "barriers_anthropogenic_upstr_count",                    "Barriers Anthropogenic Upstr Count",       NA,       NA,                                                                                                                                                                                        "A count of the barrier crossings upstream of the given crossing",
                                                 "gradient",                                              "Gradient",       NA,       NA,                                                                                                                                                                                                                                  "Stream slope at point",
                                         "total_network_km",                                    "Total Network (km)",       NA,       NA,                                                                                                                                                                                                       "Total length of stream network upstream of point",
                                          "total_stream_km",                                     "Total Stream (km)",       NA,       NA,                                                                                                                                                "Total length of streams and rivers upstream of point (does not include network connectors in lakes etc)",
                                   "total_lakereservoir_ha",                             "Total Lake Reservoir (ha)",       NA,       NA,                                                                                                                                                                                                      "Total area lakes and reservoirs upstream of point",
                                         "total_wetland_ha",                                    "Total Wetland (ha)",       NA,       NA,                                                                                                                                                                                                                  "Total area wetlands upstream of point",
                        "total_slopeclass03_waterbodies_km",                   "Total Slopeclass03 Waterbodies (km)",       NA,       NA,                                                                                                                                            "Total length of stream connectors (in waterbodies) potentially accessible upstream of point with slope 0-3%",
                                    "total_slopeclass03_km",                               "Total Slopeclass03 (km)",       NA,       NA,                                                                                                                                                                        "Total length of stream potentially accessible upstream of point with slope 0-3%",
                                    "total_slopeclass05_km",                               "Total Slopeclass05 (km)",       NA,       NA,                                                                                                                                                                        "Total length of stream potentially accessible upstream of point with slope 3-5%",
                                    "total_slopeclass08_km",                               "Total Slopeclass08 (km)",       NA,       NA,                                                                                                                                                                        "Total length of stream potentially accessible upstream of point with slope 5-8%",
                                    "total_slopeclass15_km",                               "Total Slopeclass15 (km)",       NA,       NA,                                                                                                                                                                       "Total length of stream potentially accessible upstream of point with slope 8-15%",
                                    "total_slopeclass22_km",                               "Total Slopeclass22 (km)",       NA,       NA,                                                                                                                                                                      "Total length of stream potentially accessible upstream of point with slope 15-22%",
                                    "total_slopeclass30_km",                               "Total Slopeclass30 (km)",       NA,       NA,                                                                                                                                                                      "Total length of stream potentially accessible upstream of point with slope 22-30%",
                      "total_belowupstrbarriers_network_km",                     "Total Below Barriers Network (km)",       NA,       NA,                                                                                                                                     "Total length of stream network potentially accessible upstream of point and below any additional upstream barriers",
                       "total_belowupstrbarriers_stream_km",                      "Total Below Barriers Stream (km)",       NA,       NA,                                                                              "Total length of streams and rivers potentially accessible upstream of point and below any additional upstream barriers (does not include network connectors in lakes etc)",
                "total_belowupstrbarriers_lakereservoir_ha",              "Total Below Barriers Lake Reservoir (ha)",       NA,       NA,                                                                                                                                    "Total area lakes and reservoirs potentially accessible upstream of point and below any additional upstream barriers",
                      "total_belowupstrbarriers_wetland_ha",                     "Total Below Barriers Wetland (ha)",       NA,       NA,                                                                                                                                                "Total area wetlands potentially accessible upstream of point and below any additional upstream barriers",
     "total_belowupstrbarriers_slopeclass03_waterbodies_km",    "Total Below Barriers Slopeclass03 Waterbodies (km)",       NA,       NA,                                                                                                "Total length of stream connectors (in waterbodies) potentially accessible upstream of point and below any additional upstream barriers, with slope 0-3%",
                 "total_belowupstrbarriers_slopeclass03_km",                "Total Below Barriers Slopeclass03 (km)",       NA,       NA,                                                                                                                            "Total length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 0-3%",
                 "total_belowupstrbarriers_slopeclass05_km",                "Total Below Barriers Slopeclass05 (km)",       NA,       NA,                                                                                                                            "Total length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 3-5%",
                 "total_belowupstrbarriers_slopeclass08_km",                "Total Below Barriers Slopeclass08 (km)",       NA,       NA,                                                                                                                            "Total length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 5-8%",
                 "total_belowupstrbarriers_slopeclass15_km",                "Total Below Barriers Slopeclass15 (km)",       NA,       NA,                                                                                                                           "Total length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 8-15%",
                 "total_belowupstrbarriers_slopeclass22_km",                "Total Below Barriers Slopeclass22 (km)",       NA,       NA,                                                                                                                          "Total length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 15-22%",
                 "total_belowupstrbarriers_slopeclass30_km",                "Total Below Barriers Slopeclass30 (km)",       NA,       NA,                                                                                                                          "Total length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 22-30%",
                                          "access_model_bt",                                       "Access Model Bt",       NA,       NA,                                                                                                                                                                                                         "Modelled accessibility to Bull Trout (25% max)",
                                            "bt_network_km",                                       "BT Network (km)",       NA,       NA,                                                                                                                                                              "Bull Trout model, total length of stream network potentially accessible upstream of point",
                                             "bt_stream_km",                                        "BT Stream (km)",       NA,       NA,                                                                                                       "Bull Trout model, total length of streams and rivers potentially accessible upstream of point (does not include network connectors in lakes etc)",
                                      "bt_lakereservoir_ha",                                "BT Lake Reservoir (ha)",       NA,       NA,                                                                                                                                                             "Bull Trout model, total area lakes and reservoirs potentially accessible upstream of point",
                                            "bt_wetland_ha",                                       "BT Wetland (ha)",       NA,       NA,                                                                                                                                                                         "Bull Trout model, total area wetlands potentially accessible upstream of point",
                           "bt_slopeclass03_waterbodies_km",                      "BT Slopeclass03 Waterbodies (km)",       NA,       NA,                                                                                                                                "Bull Trout model, length of stream connectors (in waterbodies) potentially accessible upstream of point with slope 0-3%",
                                       "bt_slopeclass03_km",                                  "BT Slopeclass03 (km)",       NA,       NA,                                                                                                                                                            "Bull Trout model, length of stream potentially accessible upstream of point with slope 0-3%",
                                       "bt_slopeclass05_km",                                  "BT Slopeclass05 (km)",       NA,       NA,                                                                                                                                                            "Bull Trout model, length of stream potentially accessible upstream of point with slope 3-5%",
                                       "bt_slopeclass08_km",                                  "BT Slopeclass08 (km)",       NA,       NA,                                                                                                                                                            "Bull Trout model, length of stream potentially accessible upstream of point with slope 5-8%",
                                       "bt_slopeclass15_km",                                  "BT Slopeclass15 (km)",       NA,       NA,                                                                                                                                                           "Bull Trout model, length of stream potentially accessible upstream of point with slope 8-15%",
                                       "bt_slopeclass22_km",                                  "BT Slopeclass22 (km)",       NA,       NA,                                                                                                                                                          "Bull Trout model, length of stream potentially accessible upstream of point with slope 15-22%",
                                       "bt_slopeclass30_km",                                  "BT Slopeclass30 (km)",       NA,       NA,                                                                                                                                                          "Bull Trout model, length of stream potentially accessible upstream of point with slope 22-30%",
                         "bt_belowupstrbarriers_network_km",                        "BT Below Barriers Network (km)",       NA,       NA,                                                                                                                   "Bull Trout model, total length of stream network potentially accessible upstream of point and below any additional upstream barriers",
                          "bt_belowupstrbarriers_stream_km",                         "BT Below Barriers Stream (km)",       NA,       NA,                                                            "Bull Trout model, total length of streams and rivers potentially accessible upstream of point and below any additional upstream barriers (does not include network connectors in lakes etc)",
                   "bt_belowupstrbarriers_lakereservoir_ha",                 "BT Below Barriers Lake Reservoir (ha)",       NA,       NA,                                                                                                                  "Bull Trout model, total area lakes and reservoirs potentially accessible upstream of point and below any additional upstream barriers",
                         "bt_belowupstrbarriers_wetland_ha",                        "BT Below Barriers Wetland (ha)",       NA,       NA,                                                                                                                              "Bull Trout model, total area wetlands potentially accessible upstream of point and below any additional upstream barriers",
        "bt_belowupstrbarriers_slopeclass03_waterbodies_km",       "BT Below Barriers Slopeclass03 Waterbodies (km)",       NA,       NA,                                                                                    "Bull Trout model, length of stream connectors (in waterbodies) potentially accessible upstream of point and below any additional upstream barriers, with slope 0-3%",
                    "bt_belowupstrbarriers_slopeclass03_km",                   "BT Below Barriers Slopeclass03 (km)",       NA,       NA,                                                                                                                "Bull Trout model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 0-3%",
                    "bt_belowupstrbarriers_slopeclass05_km",                   "BT Below Barriers Slopeclass05 (km)",       NA,       NA,                                                                                                                "Bull Trout model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 3-5%",
                    "bt_belowupstrbarriers_slopeclass08_km",                   "BT Below Barriers Slopeclass08 (km)",       NA,       NA,                                                                                                                "Bull Trout model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 5-8%",
                    "bt_belowupstrbarriers_slopeclass15_km",                   "BT Below Barriers Slopeclass15 (km)",       NA,       NA,                                                                                                               "Bull Trout model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 8-15%",
                    "bt_belowupstrbarriers_slopeclass22_km",                   "BT Below Barriers Slopeclass22 (km)",       NA,       NA,                                                                                                              "Bull Trout model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 15-22%",
                    "bt_belowupstrbarriers_slopeclass30_km",                   "BT Below Barriers Slopeclass30 (km)",       NA,       NA,                                                                                                              "Bull Trout model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 22-30%",
                                    "access_model_ch_co_sk",                                 "Access Model CH CO Sk",       NA,       NA,                                                                                                                                                                                        "Modelled accessibility to Chinook/Coho/Sockeye Salmon (15% max)",
                                      "ch_co_sk_network_km",                                 "CH CO SK Network (km)",       NA,       NA,                                                                                                                                             "Chinook/Coho/Sockeye salmon model, total length of stream network potentially accessible upstream of point",
                                       "ch_co_sk_stream_km",                                  "CH CO SK Stream (km)",       NA,       NA,                                                                                      "Chinook/Coho/Sockeye salmon model, total length of streams and rivers potentially accessible upstream of point (does not include network connectors in lakes etc)",
                                "ch_co_sk_lakereservoir_ha",                          "CH CO SK Lake Reservoir (ha)",       NA,       NA,                                                                                                                                            "Chinook/Coho/Sockeye salmon model, total area lakes and reservoirs potentially accessible upstream of point",
                                      "ch_co_sk_wetland_ha",                                 "CH CO SK Wetland (ha)",       NA,       NA,                                                                                                                                                        "Chinook/Coho/Sockeye salmon model, total area wetlands potentially accessible upstream of point",
                     "ch_co_sk_slopeclass03_waterbodies_km",                "CH CO SK Slopeclass03 Waterbodies (km)",       NA,       NA,                                                                                                               "Chinook/Coho/Sockeye salmon model, length of stream connectors (in waterbodies) potentially accessible upstream of point with slope 0-3%",
                                 "ch_co_sk_slopeclass03_km",                            "CH CO SK Slopeclass03 (km)",       NA,       NA,                                                                                                                                           "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point with slope 0-3%",
                                 "ch_co_sk_slopeclass05_km",                            "CH CO SK Slopeclass05 (km)",       NA,       NA,                                                                                                                                           "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point with slope 3-5%",
                                 "ch_co_sk_slopeclass08_km",                            "CH CO SK Slopeclass08 (km)",       NA,       NA,                                                                                                                                           "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point with slope 5-8%",
                                 "ch_co_sk_slopeclass15_km",                            "CH CO SK Slopeclass15 (km)",       NA,       NA,                                                                                                                                          "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point with slope 8-15%",
                                 "ch_co_sk_slopeclass22_km",                            "CH CO SK Slopeclass22 (km)",       NA,       NA,                                                                                                                                         "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point with slope 15-22%",
                                 "ch_co_sk_slopeclass30_km",                            "CH CO SK Slopeclass30 (km)",       NA,       NA,                                                                                                                                         "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point with slope 22-30%",
                   "ch_co_sk_belowupstrbarriers_network_km",                  "CH CO SK Below Barriers Network (km)",       NA,       NA,                                                                                                  "Chinook/Coho/Sockeye salmon model, total length of stream network potentially accessible upstream of point and below any additional upstream barriers",
                    "ch_co_sk_belowupstrbarriers_stream_km",                   "CH CO SK Below Barriers Stream (km)",       NA,       NA,                                           "Chinook/Coho/Sockeye salmon model, total length of streams and rivers potentially accessible upstream of point and below any additional upstream barriers (does not include network connectors in lakes etc)",
             "ch_co_sk_belowupstrbarriers_lakereservoir_ha",           "CH CO SK Below Barriers Lake Reservoir (ha)",       NA,       NA,                                                                                                 "Chinook/Coho/Sockeye salmon model, total area lakes and reservoirs potentially accessible upstream of point and below any additional upstream barriers",
                   "ch_co_sk_belowupstrbarriers_wetland_ha",                  "CH CO SK Below Barriers Wetland (ha)",       NA,       NA,                                                                                                             "Chinook/Coho/Sockeye salmon model, total area wetlands potentially accessible upstream of point and below any additional upstream barriers",
  "ch_co_sk_belowupstrbarriers_slopeclass03_waterbodies_km", "CH CO SK Below Barriers Slopeclass03 Waterbodies (km)",       NA,       NA,                                                                   "Chinook/Coho/Sockeye salmon model, length of stream connectors (in waterbodies) potentially accessible upstream of point and below any additional upstream barriers, with slope 0-3%",
              "ch_co_sk_belowupstrbarriers_slopeclass03_km",             "CH CO SK Below Barriers Slopeclass03 (km)",       NA,       NA,                                                                                               "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 0-3%",
              "ch_co_sk_belowupstrbarriers_slopeclass05_km",             "CH CO SK Below Barriers Slopeclass05 (km)",       NA,       NA,                                                                                               "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 3-5%",
              "ch_co_sk_belowupstrbarriers_slopeclass08_km",             "CH CO SK Below Barriers Slopeclass08 (km)",       NA,       NA,                                                                                               "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 5-8%",
              "ch_co_sk_belowupstrbarriers_slopeclass15_km",             "CH CO SK Below Barriers Slopeclass15 (km)",       NA,       NA,                                                                                              "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 8-15%",
              "ch_co_sk_belowupstrbarriers_slopeclass22_km",             "CH CO SK Below Barriers Slopeclass22 (km)",       NA,       NA,                                                                                             "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 15-22%",
              "ch_co_sk_belowupstrbarriers_slopeclass30_km",             "CH CO SK Below Barriers Slopeclass30 (km)",       NA,       NA,                                                                                             "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 22-30%",
                                          "access_model_pk",                                       "Access Model Pk",       NA,       NA,                                                                                                                                                                                                        "Modelled accessibility to Pink Salmon (12% max)",
                                            "pk_network_km",                                       "Pk Network (km)",       NA,       NA,                                                                                                                                             "Chinook/Coho/Sockeye salmon model, total length of stream network potentially accessible upstream of point",
                                             "pk_stream_km",                                        "Pk Stream (km)",       NA,       NA,                                                                                      "Chinook/Coho/Sockeye salmon model, total length of streams and rivers potentially accessible upstream of point (does not include network connectors in lakes etc)",
                                      "pk_lakereservoir_ha",                                "Pk Lake Reservoir (ha)",       NA,       NA,                                                                                                                                            "Chinook/Coho/Sockeye salmon model, total area lakes and reservoirs potentially accessible upstream of point",
                                            "pk_wetland_ha",                                       "Pk Wetland (ha)",       NA,       NA,                                                                                                                                                        "Chinook/Coho/Sockeye salmon model, total area wetlands potentially accessible upstream of point",
                           "pk_slopeclass03_waterbodies_km",                      "Pk Slopeclass03 Waterbodies (km)",       NA,       NA,                                                                                                               "Chinook/Coho/Sockeye salmon model, length of stream connectors (in waterbodies) potentially accessible upstream of point with slope 0-3%",
                                       "pk_slopeclass03_km",                                  "Pk Slopeclass03 (km)",       NA,       NA,                                                                                                                                           "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point with slope 0-3%",
                                       "pk_slopeclass05_km",                                  "Pk Slopeclass05 (km)",       NA,       NA,                                                                                                                                           "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point with slope 3-5%",
                                       "pk_slopeclass08_km",                                  "Pk Slopeclass08 (km)",       NA,       NA,                                                                                                                                           "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point with slope 5-8%",
                                       "pk_slopeclass15_km",                                  "Pk Slopeclass15 (km)",       NA,       NA,                                                                                                                                          "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point with slope 8-15%",
                                       "pk_slopeclass22_km",                                  "Pk Slopeclass22 (km)",       NA,       NA,                                                                                                                                         "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point with slope 15-22%",
                                       "pk_slopeclass30_km",                                  "Pk Slopeclass30 (km)",       NA,       NA,                                                                                                                                         "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point with slope 22-30%",
                         "pk_belowupstrbarriers_network_km",                        "Pk Below Barriers Network (km)",       NA,       NA,                                                                                                  "Chinook/Coho/Sockeye salmon model, total length of stream network potentially accessible upstream of point and below any additional upstream barriers",
                          "pk_belowupstrbarriers_stream_km",                         "Pk Below Barriers Stream (km)",       NA,       NA,                                           "Chinook/Coho/Sockeye salmon model, total length of streams and rivers potentially accessible upstream of point and below any additional upstream barriers (does not include network connectors in lakes etc)",
                   "pk_belowupstrbarriers_lakereservoir_ha",                 "Pk Below Barriers Lake Reservoir (ha)",       NA,       NA,                                                                                                 "Chinook/Coho/Sockeye salmon model, total area lakes and reservoirs potentially accessible upstream of point and below any additional upstream barriers",
                         "pk_belowupstrbarriers_wetland_ha",                        "Pk Below Barriers Wetland (ha)",       NA,       NA,                                                                                                             "Chinook/Coho/Sockeye salmon model, total area wetlands potentially accessible upstream of point and below any additional upstream barriers",
        "pk_belowupstrbarriers_slopeclass03_waterbodies_km",       "Pk Below Barriers Slopeclass03 Waterbodies (km)",       NA,       NA,                                                                   "Chinook/Coho/Sockeye salmon model, length of stream connectors (in waterbodies) potentially accessible upstream of point and below any additional upstream barriers, with slope 0-3%",
                    "pk_belowupstrbarriers_slopeclass03_km",                   "Pk Below Barriers Slopeclass03 (km)",       NA,       NA,                                                                                               "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 0-3%",
                    "pk_belowupstrbarriers_slopeclass05_km",                   "Pk Below Barriers Slopeclass05 (km)",       NA,       NA,                                                                                               "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 3-5%",
                    "pk_belowupstrbarriers_slopeclass08_km",                   "Pk Below Barriers Slopeclass08 (km)",       NA,       NA,                                                                                               "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 5-8%",
                    "pk_belowupstrbarriers_slopeclass15_km",                   "Pk Below Barriers Slopeclass15 (km)",       NA,       NA,                                                                                              "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 8-15%",
                    "pk_belowupstrbarriers_slopeclass22_km",                   "Pk Below Barriers Slopeclass22 (km)",       NA,       NA,                                                                                             "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 15-22%",
                    "pk_belowupstrbarriers_slopeclass30_km",                   "Pk Below Barriers Slopeclass30 (km)",       NA,       NA,                                                                                             "Chinook/Coho/Sockeye salmon model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 22-30%",
                                          "access_model_st",                                       "Access Model St",       NA,       NA,                                                                                                                                                                                                          "Modelled accessibility to Steelhead (20% max)",
                                            "st_network_km",                                       "ST Network (km)",      10L,       1L,                                                                                                                                                               "Steelhead model, total length of stream network potentially accessible upstream of point",
                                             "st_stream_km",                                        "ST Stream (km)",       NA,       NA,                                                                                                        "Steelhead model, total length of streams and rivers potentially accessible upstream of point (does not include network connectors in lakes etc)",
                                      "st_lakereservoir_ha",                                "ST Lake Reservoir (ha)",      20L,       1L,                                                                                                                                                              "Steelhead model, total area lakes and reservoirs potentially accessible upstream of point",
                                            "st_wetland_ha",                                       "ST Wetland (ha)",      30L,       1L,                                                                                                                                                                          "Steelhead model, total area wetlands potentially accessible upstream of point",
                           "st_slopeclass03_waterbodies_km",                      "ST Slopeclass03 Waterbodies (km)",      40L,       1L,                                                                                                                                 "Steelhead model, length of stream connectors (in waterbodies) potentially accessible upstream of point with slope 0-3%",
                                       "st_slopeclass03_km",                                  "ST Slopeclass03 (km)",      50L,       1L,                                                                                                                                                             "Steelhead model, length of stream potentially accessible upstream of point with slope 0-3%",
                                       "st_slopeclass05_km",                                  "ST Slopeclass05 (km)",      60L,       1L,                                                                                                                                                             "Steelhead model, length of stream potentially accessible upstream of point with slope 3-5%",
                                       "st_slopeclass08_km",                                  "ST Slopeclass08 (km)",      70L,       1L,                                                                                                                                                             "Steelhead model, length of stream potentially accessible upstream of point with slope 5-8%",
                                       "st_slopeclass15_km",                                  "ST Slopeclass15 (km)",       NA,       NA,                                                                                                                                                            "Steelhead model, length of stream potentially accessible upstream of point with slope 8-15%",
                                       "st_slopeclass22_km",                                  "ST Slopeclass22 (km)",       NA,       NA,                                                                                                                                                           "Steelhead model, length of stream potentially accessible upstream of point with slope 15-22%",
                                       "st_slopeclass30_km",                                  "ST Slopeclass30 (km)",       NA,       NA,                                                                                                                                                           "Steelhead model, length of stream potentially accessible upstream of point with slope 22-30%",
                         "st_belowupstrbarriers_network_km",                        "ST Below Barriers Network (km)",      10L,       2L,                                                                                                                    "Steelhead model, total length of stream network potentially accessible upstream of point and below any additional upstream barriers",
                          "st_belowupstrbarriers_stream_km",                         "ST Below Barriers Stream (km)",       NA,       NA,                                                             "Steelhead model, total length of streams and rivers potentially accessible upstream of point and below any additional upstream barriers (does not include network connectors in lakes etc)",
                   "st_belowupstrbarriers_lakereservoir_ha",                 "ST Below Barriers Lake Reservoir (ha)",      20L,       2L,                                                                                                                   "Steelhead model, total area lakes and reservoirs potentially accessible upstream of point and below any additional upstream barriers",
                         "st_belowupstrbarriers_wetland_ha",                        "ST Below Barriers Wetland (ha)",      30L,       2L,                                                                                                                               "Steelhead model, total area wetlands potentially accessible upstream of point and below any additional upstream barriers",
        "st_belowupstrbarriers_slopeclass03_waterbodies_km",       "ST Below Barriers Slopeclass03 Waterbodies (km)",      40L,       2L,                                                                                     "Steelhead model, length of stream connectors (in waterbodies) potentially accessible upstream of point and below any additional upstream barriers, with slope 0-3%",
                    "st_belowupstrbarriers_slopeclass03_km",                   "ST Below Barriers Slopeclass03 (km)",      50L,       2L,                                                                                                                 "Steelhead model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 0-3%",
                    "st_belowupstrbarriers_slopeclass05_km",                   "ST Below Barriers Slopeclass05 (km)",      60L,       2L,                                                                                                                 "Steelhead model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 3-5%",
                    "st_belowupstrbarriers_slopeclass08_km",                   "ST Below Barriers Slopeclass08 (km)",      70L,       2L,                                                                                                                 "Steelhead model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 5-8%",
                    "st_belowupstrbarriers_slopeclass15_km",                   "ST Below Barriers Slopeclass15 (km)",       NA,       NA,                                                                                                                "Steelhead model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 8-15%",
                    "st_belowupstrbarriers_slopeclass22_km",                   "ST Below Barriers Slopeclass22 (km)",       NA,       NA,                                                                                                               "Steelhead model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 15-22%",
                    "st_belowupstrbarriers_slopeclass30_km",                   "ST Below Barriers Slopeclass30 (km)",       NA,       NA,                                                                                                               "Steelhead model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 22-30%",
                                         "access_model_wct",                                      "Access Model Wct",       NA,       NA,                                                                                                                                                  "Modelled accessibility to West Slope Cutthroat Trout (20% max or downstream of known WCT observation)",
                                           "wct_network_km",                                      "WCT Network (km)",       NA,       NA,                                                                                                                                                "Westslope Cuthroat Trout model, total length of stream network potentially accessible upstream of point",
                                            "wct_stream_km",                                       "WCT Stream (km)",       NA,       NA,                                                                                         "Westslope Cuthroat Trout model, total length of streams and rivers potentially accessible upstream of point (does not include network connectors in lakes etc)",
                                     "wct_lakereservoir_ha",                               "WCT Lake Reservoir (ha)",       NA,       NA,                                                                                                                                               "Westslope Cuthroat Trout model, total area lakes and reservoirs potentially accessible upstream of point",
                                           "wct_wetland_ha",                                      "WCT Wetland (ha)",       NA,       NA,                                                                                                                                                           "Westslope Cuthroat Trout model, total area wetlands potentially accessible upstream of point",
                          "wct_slopeclass03_waterbodies_km",                     "WCT Slopeclass03 Waterbodies (km)",       NA,       NA,                                                                                                                 "Westslope Cutthroat Trout model, length of stream connectors (in waterbodies) potentially accessible upstream of point with slope 0-3%",
                                      "wct_slopeclass03_km",                                 "WCT Slopeclass03 (km)",       NA,       NA,                                                                                                                                             "Westslope Cutthroat Trout model, length of stream potentially accessible upstream of point with slope 0-3%",
                                      "wct_slopeclass05_km",                                 "WCT Slopeclass05 (km)",       NA,       NA,                                                                                                                                             "Westslope Cutthroat Trout model, length of stream potentially accessible upstream of point with slope 3-5%",
                                      "wct_slopeclass08_km",                                 "WCT Slopeclass08 (km)",       NA,       NA,                                                                                                                                             "Westslope Cutthroat Trout model, length of stream potentially accessible upstream of point with slope 5-8%",
                                      "wct_slopeclass15_km",                                 "WCT Slopeclass15 (km)",       NA,       NA,                                                                                                                                            "Westslope Cutthroat Trout model, length of stream potentially accessible upstream of point with slope 8-15%",
                                      "wct_slopeclass22_km",                                 "WCT Slopeclass22 (km)",       NA,       NA,                                                                                                                                           "Westslope Cutthroat Trout model, length of stream potentially accessible upstream of point with slope 15-22%",
                                      "wct_slopeclass30_km",                                 "WCT Slopeclass30 (km)",       NA,       NA,                                                                                                                                           "Westslope Cutthroat Trout model, length of stream potentially accessible upstream of point with slope 22-30%",
                        "wct_belowupstrbarriers_network_km",                       "WCT Below Barriers Network (km)",       NA,       NA,                                                                                                    "Westslope Cutthroat Trout model, total length of stream network potentially accessible upstream of point and below any additional upstream barriers",
                         "wct_belowupstrbarriers_stream_km",                        "WCT Below Barriers Stream (km)",       NA,       NA,                                              "Westslope Cuthroat Trout model, total length of streams and rivers potentially accessible upstream of point and below any additional upstream barriers (does not include network connectors in lakes etc)",
                  "wct_belowupstrbarriers_lakereservoir_ha",                "WCT Below Barriers Lake Reservoir (ha)",       NA,       NA,                                                                                                   "Westslope Cutthroat Trout model, total area lakes and reservoirs potentially accessible upstream of point and below any additional upstream barriers",
                        "wct_belowupstrbarriers_wetland_ha",                       "WCT Below Barriers Wetland (ha)",       NA,       NA,                                                                                                               "Westslope Cutthroat Trout model, total area wetlands potentially accessible upstream of point and below any additional upstream barriers",
       "wct_belowupstrbarriers_slopeclass03_waterbodies_km",      "WCT Below Barriers Slopeclass03 Waterbodies (km)",       NA,       NA,                                                                     "Westslope Cutthroat Trout model, length of stream connectors (in waterbodies) potentially accessible upstream of point and below any additional upstream barriers, with slope 0-3%",
                   "wct_belowupstrbarriers_slopeclass03_km",                  "WCT Below Barriers Slopeclass03 (km)",       NA,       NA,                                                                                                 "Westslope Cutthroat Trout model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 0-3%",
                   "wct_belowupstrbarriers_slopeclass05_km",                  "WCT Below Barriers Slopeclass05 (km)",       NA,       NA,                                                                                                 "Westslope Cutthroat Trout model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 3-5%",
                   "wct_belowupstrbarriers_slopeclass08_km",                  "WCT Below Barriers Slopeclass08 (km)",       NA,       NA,                                                                                                 "Westslope Cutthroat Trout model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 5-8%",
                   "wct_belowupstrbarriers_slopeclass15_km",                  "WCT Below Barriers Slopeclass15 (km)",       NA,       NA,                                                                                                "Westslope Cutthroat Trout model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 8-15%",
                   "wct_belowupstrbarriers_slopeclass22_km",                  "WCT Below Barriers Slopeclass22 (km)",       NA,       NA,                                                                                               "Westslope Cutthroat Trout model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 15-22%",
                   "wct_belowupstrbarriers_slopeclass30_km",                  "WCT Below Barriers Slopeclass30 (km)",       NA,       NA,                                                                                               "Westslope Cutthroat Trout model, length of stream potentially accessible upstream of point and below any additional upstream barriers, with slope 22-30%",
                                           "ch_spawning_km",                                      "CH Spawning (km)",     110L,       1L,                                                                                                                                                                      "Length of stream upstream of point modelled as potential Chinook spawning habitat",
                                            "ch_rearing_km",                                       "CH Rearing (km)",     120L,       1L,                                                                                                                                                                       "Length of stream upstream of point modelled as potential Chinook rearing habitat",
                        "ch_spawning_belowupstrbarriers_km",                       "CH Spawning Below Barriers (km)",     110L,       2L,                                                                                                                          "Length of stream upstream of point and below any additional upstream barriers, modelled as potential Chinook spawning habitat",
                         "ch_rearing_belowupstrbarriers_km",                        "CH Rearing Below Barriers (km)",     120L,       2L,                                                                                                                           "Length of stream upstream of point and below any additional upstream barriers, modelled as potential Chinook rearing habitat",
                                           "co_spawning_km",                                      "CO Spawning (km)",     130L,       1L,                                                                                                                                                                         "Length of stream upstream of point modelled as potential Coho spawning habitat",
                                            "co_rearing_km",                                       "CO Rearing (km)",     140L,       1L,                                                                                                                                                                          "Length of stream upstream of point modelled as potential Coho rearing habitat",
                                            "co_rearing_ha",                                       "CO Rearing (ha)",     145L,       1L,                                                                                                                                                                          "Area of wetlands upstream of point modelled as potential Coho rearing habitat",
                        "co_spawning_belowupstrbarriers_km",                       "CO Spawning Below Barriers (km)",     130L,       2L,                                                                                                                             "Length of stream upstream of point and below any additional upstream barriers, modelled as potential Coho spawning habitat",
                         "co_rearing_belowupstrbarriers_km",                        "CO Rearing Below Barriers (km)",     140L,       2L,                                                                                                                              "Length of stream upstream of point and below any additional upstream barriers, modelled as potential Coho rearing habitat",
                         "co_rearing_belowupstrbarriers_ha",                        "CO Rearing Below Barriers (ha)",     145L,       2L,                                                                                                                              "Area of wetlands upstream of point and below any additional upstream barriers, modelled as potential Coho rearing habitat",
                                           "sk_spawning_km",                                      "SK Spawning (km)",     150L,       1L,                                                                                                                                                                      "Length of stream upstream of point modelled as potential Sockeye spawning habitat",
                                            "sk_rearing_km",                                       "SK Rearing (km)",     160L,       1L,                                                                                                                                                                       "Length of stream upstream of point modelled as potential Sockeye rearing habitat",
                                            "sk_rearing_ha",                                       "SK Rearing (ha)",     165L,       1L,                                                                                                                                                                          "Area of lakes upstream of point modelled as potential Sockeye rearing habitat",
                        "sk_spawning_belowupstrbarriers_km",                       "SK Spawning Below Barriers (km)",     150L,       2L,                                                                                                                          "Length of stream upstream of point and below any additional upstream barriers, modelled as potential Sockeye spawning habitat",
                         "sk_rearing_belowupstrbarriers_km",                        "SK Rearing Below Barriers (km)",     160L,       2L,                                                                                                                           "Length of stream upstream of point and below any additional upstream barriers, modelled as potential Sockeye rearing habitat",
                         "sk_rearing_belowupstrbarriers_ha",                        "SK Rearing Below Barriers (ha)",     165L,       2L,                                                                                                                              "Area of lakes upstream of point and below any additional upstream barriers, modelled as potential Sockeye rearing habitat",
                                           "st_spawning_km",                                      "ST Spawning (km)",      80L,       1L,                                                                                                                                                                    "Length of stream upstream of point modelled as potential Steelhead spawning habitat",
                                            "st_rearing_km",                                       "ST Rearing (km)",      90L,       1L,                                                                                                                                                                     "Length of stream upstream of point modelled as potential Steelhead rearing habitat",
                        "st_spawning_belowupstrbarriers_km",                       "ST Spawning Below Barriers (km)",      80L,       2L,                                                                                                                        "Length of stream upstream of point and below any additional upstream barriers, modelled as potential Steelhead spawning habitat",
                         "st_rearing_belowupstrbarriers_km",                        "ST Rearing Below Barriers (km)",      90L,       2L,                                                                                                                         "Length of stream upstream of point and below any additional upstream barriers, modelled as potential Steelhead rearing habitat",
                                          "wct_spawning_km",                                     "WCT Spawning (km)",       NA,       NA,                                                                                                                                                          "Length of stream upstream of point modelled as potential Westslope Cutthroat spawning habitat",
                                           "wct_rearing_km",                                      "WCT Rearing (km)",       NA,       NA,                                                                                                                                                           "Length of stream upstream of point modelled as potential Westslope Cutthroat rearing habitat",
                       "wct_spawning_belowupstrbarriers_km",                      "WCT Spawning Below Barriers (km)",       NA,       NA,                                                                                                              "Length of stream upstream of point and below any additional upstream barriers, modelled as potential Westslope Cutthroat spawning habitat",
                        "wct_rearing_belowupstrbarriers_km",                       "WCT Rearing Below Barriers (km)",       NA,       NA,                                                                                                               "Length of stream upstream of point and below any additional upstream barriers, modelled as potential Westslope Cutthroat rearing habitat",
                                          "all_spawning_km",                                     "All Spawning (km)",     190L,       1L,                                                                                                                                                        "Length of stream upstream of point modelled as potential spawning habitat (all CH,CO,SK,ST,WCT)",
                       "all_spawning_belowupstrbarriers_km",                      "All Spawning Below Barriers (km)",     190L,       2L,                                                                                                                                                         "Length of stream upstream of point modelled as potential rearing habitat (all CH,CO,SK,ST,WCT)",
                                           "all_rearing_km",                                      "All Rearing (km)",     200L,       1L,                                                                                                            "Length of stream upstream of point and below any additional upstream barriers, modelled as potential spawning habitat (all CH,CO,SK,ST,WCT)",
                        "all_rearing_belowupstrbarriers_km",                       "All Rearing Below Barriers (km)",     200L,       2L,                                                                                                             "Length of stream upstream of point and below any additional upstream barriers, modelled as potential rearing habitat (all CH,CO,SK,ST,WCT)",
                                   "all_spawningrearing_km",                             "All Spawning Rearing (km)",     210L,       1L,                                                                                                                                                                                           "Length of all spawning and rearing habitat upstream of point",
                "all_spawningrearing_belowupstrbarriers_km",              "All Spawning Rearing Below Barriers (km)",     210L,       2L,                                                                                                                                                                                           "Length of all spawning and rearing habitat upstream of point",
                           "wct_betweenbarriers_network_km",                     "WCT Between Barriers Network (km)",       NA,       NA,                                                                                                            "Westslope Cutthroat Trout model, total length of potentially accessible stream network between crossing and all in-stream adjacent barriers",
                          "wct_spawning_betweenbarriers_km",                    "WCT Spawning Between Barriers (km)",       NA,       NA,                                                                                                                                 "Westslope Cutthroat Trout model, total length of spawning habitat between crossing and all in-stream adjacent barriers",
                           "wct_rearing_betweenbarriers_km",                     "WCT Rearing Between Barriers (km)",       NA,       NA,                                                                                                                                  "Westslope Cutthroat Trout model, total length of rearing habitat between crossing and all in-stream adjacent barriers",
                   "wct_spawningrearing_betweenbarriers_km",            "WCT Spawning Rearing Between Barriers (km)",       NA,       NA,                                                                                                                     "Westslope Cutthroat Trout model, total length of spawning and rearing habitat between crossing and all in-stream adjacent barriers",
                          "all_spawningrearing_per_barrier",                      "All Spawning Rearing Per Barrier",       NA,       NA, "If the given barrier and all barriers downstream were remediated, the amount of connected spawning/rearing habitat that would be added, per barrier. (ie the sum of all_spawningrearing_belowupstrbarriers_km for all barriers, divided by n barriers)"
  )

usethis::use_data(fpr_xref_crossings)
