#' This is a table that cross references the names PSCIS submissioni template to the bc data catalogue names to names used in reporting.  Also has columns that reference untidy table ids for join for two column table.
#'
#' @name xref_names_pscis
#' @docType data
#' @author Al Irvine \email{al@newgraphenvironment.com}
#' @references \url{https://www2.gov.bc.ca/gov/content/environment/plants-animals-ecosystems/fish/aquatic-habitat-management/fish-passage/fish-passage-technical/assessment-projects}
#' @keywords data
xref_names_pscis <- tibble::tribble(
                                              ~bcdata,                               ~spdsht,                 ~report, ~id_join, ~id_side,       ~type,
                                                 "id",                                    NA,                      NA,       NA,       NA,      "NULL",
                             "funding_project_number",                                    NA,                      NA,       NA,       NA, "character",
                                    "funding_project",                                    NA,                      NA,       NA,       NA, "character",
                                         "project_id",                                    NA,                      NA,       NA,       NA, "character",
                                     "funding_source",                                    NA,                      NA,       NA,       NA, "character",
                             "responsible_party_name",                                    NA,                      NA,       NA,       NA, "character",
                                    "consultant_name",                                    NA,                      NA,       NA,       NA, "character",
                                    "assessment_date",                                "date",                  "Date",       1L,       1L,      "Date",
                                 "stream_crossing_id",                   "pscis_crossing_id",              "PSCIS ID",       2L,       1L,   "numeric",
                                      "assessment_id",                                    NA,                      NA,       NA,       NA,      "NULL",
                        "external_crossing_reference",               "my_crossing_reference",           "External ID",       3L,       1L,   "numeric",
                                       "crew_members",                        "crew_members",                  "Crew",       5L,       1L, "character",
                                           "utm_zone",                            "utm_zone",              "UTM Zone",       6L,       1L,   "numeric",
                                        "utm_easting",                             "easting",               "Easting",       7L,       1L,   "numeric",
                                       "utm_northing",                            "northing",              "Northing",       8L,       1L,   "numeric",
                            "location_confidence_ind",                                    NA,                      NA,       NA,       NA,      "NULL",
                                        "stream_name",                         "stream_name",                "Stream",       9L,       1L, "character",
                                          "road_name",                           "road_name",                  "Road",      10L,       1L, "character",
                                       "road_km_mark",                        "road_km_mark",                      NA,       NA,       NA,   "numeric",
                                        "road_tenure",                         "road_tenure",           "Road Tenure",      11L,       1L, "character",
                                 "crossing_type_code",                       "crossing_type",         "Crossing Type",       NA,       NA, "character",
                                 "crossing_type_desc",                                    NA,                      NA,       NA,       NA,      "NULL",
                              "crossing_subtype_code",                    "crossing_subtype",     "Crossing Sub Type",       1L,       2L, "character",
                              "crossing_subtype_desc",                                    NA,                      NA,       NA,       NA,      "NULL",
                                   "diameter_or_span",             "diameter_or_span_meters",          "Diameter (m)",       2L,       2L,   "numeric",
                                    "length_or_width",              "length_or_width_meters",            "Length (m)",       3L,       2L,   "numeric",
                        "continuous_embeddedment_ind",      "continuous_embeddedment_yes_no",              "Embedded",       5L,       2L, "character",
                         "average_depth_embededdment",   "average_depth_embededdment_meters",    "Depth Embedded (m)",       6L,       2L,   "numeric",
                               "resemble_channel_ind",             "resemble_channel_yes_no",      "Resemble Channel",       7L,       2L, "character",
                                    "backwatered_ind",                  "backwatered_yes_no",           "Backwatered",       8L,       2L, "character",
                             "percentage_backwatered",              "percentage_backwatered",   "Percent Backwatered",       9L,       2L,   "numeric",
                                         "fill_depth",                   "fill_depth_meters",        "Fill Depth (m)",      10L,       2L,   "numeric",
                                        "outlet_drop",                  "outlet_drop_meters",       "Outlet Drop (m)",      11L,       2L,   "numeric",
                                  "outlet_pool_depth",             "outlet_pool_depth_0_01m", "Outlet Pool Depth (m)",      12L,       2L,   "numeric",
                                     "inlet_drop_ind",                   "inlet_drop_yes_no",            "Inlet Drop",      13L,       2L, "character",
                                      "culvert_slope",               "culvert_slope_percent",             "Slope (%)",      14L,       2L,   "numeric",
                           "downstream_channel_width",     "downstream_channel_width_meters",     "Channel Width (m)",      12L,       1L,   "numeric",
                                       "stream_slope",                        "stream_slope",      "Stream Slope (%)",      13L,       1L,   "numeric",
                                "beaver_activity_ind",              "beaver_activity_yes_no",       "Beaver Activity",      14L,       1L, "character",
                                  "fish_observed_ind",                "fish_observed_yes_no",          "Fish Sighted",       NA,       NA, "character",
                                   "valley_fill_code",                         "valley_fill",           "Valley Fill",      15L,       2L, "character",
                              "valley_fill_code_desc",                                    NA,                      NA,       NA,       NA, "character",
                                 "habitat_value_code",                       "habitat_value",         "Habitat Value",      15L,       1L, "character",
                                 "habitat_value_desc",                                    NA,                      NA,       NA,       NA, "character",
                                 "stream_width_ratio",                  "stream_width_ratio",                   "SWR",       NA,       NA,   "numeric",
                           "stream_width_ratio_score",                                    NA,                 "Score",       NA,       NA,   "numeric",
                               "culvert_length_score",                "culvert_length_score",                 "Score",       NA,       NA,   "numeric",
                                        "embed_score",                         "embed_score",                 "Score",       NA,       NA,   "numeric",
                                  "outlet_drop_score",                   "outlet_drop_score",                 "Score",       NA,       NA,   "numeric",
                                "culvert_slope_score",                 "culvert_slope_score",                 "Score",       NA,       NA,   "numeric",
                                        "final_score",                         "final_score",           "Final score",      16L,       1L,   "numeric",
                                "barrier_result_code",                      "barrier_result",        "Barrier Result",      16L,       2L, "character",
                         "barrier_result_description",                                    NA,                      NA,       NA,       NA, "character",
                                  "crossing_fix_code",                                    NA,                      NA,       NA,       NA, "character",
                                  "crossing_fix_desc",                        "crossing_fix",              "Fix type",      17L,       1L, "character",
                       "recommended_diameter_or_span", "recommended_diameter_or_span_meters",   "Fix Span / Diameter",      17L,       2L,   "numeric",
                                 "assessment_comment",                  "assessment_comment",               "Comment",       NA,       NA, "character",
                                         "ecocat_url",                                    NA,                      NA,       NA,       NA, "character",
                                     "image_view_url",                                    NA,                      NA,       NA,       NA, "character",
                               "current_pscis_status",                                    NA,                      NA,       NA,       NA, "character",
                         "current_crossing_type_code",                                    NA,                      NA,       NA,       NA, "character",
                         "current_crossing_type_desc",                                    NA,                      NA,       NA,       NA, "character",
                      "current_crossing_subtype_code",                                    NA,                      NA,       NA,       NA, "character",
                      "current_crossing_subtype_desc",                                    NA,                      NA,       NA,       NA, "character",
                        "current_barrier_result_code",                                    NA,                      NA,       NA,       NA, "character",
                        "current_barrier_description",                                    NA,                      NA,       NA,       NA, "character",
                                       "feature_code",                                    NA,                      NA,       NA,       NA, "character",
                                           "objectid",                                    NA,                      NA,       NA,       NA, "character",
                                   "se_anno_cad_data",                                    NA,                      NA,       NA,       NA, "character",
                                           "geometry",                                    NA,                      NA,       NA,       NA,      "NULL"
                      )



usethis::use_data(xref_names_pscis, overwrite = TRUE)
