#' This is a table that cross references the names PSCIS submissioni template to the bc data catalogue names to names used in reporting.  Also has columns that reference untidy table ids for join for two column table.
#'
#' @name xref_names_pscis
#' @docType data
#' @author Al Irvine \email{al@newgraphenvironment.com}
#' @references \url{https://www2.gov.bc.ca/gov/content/environment/plants-animals-ecosystems/fish/aquatic-habitat-management/fish-passage/fish-passage-technical/assessment-projects}
#' @keywords data
xref_names_pscis <- tibble::tribble(
                                        ~bcdata,                               ~spdsht,                 ~report, ~id_join, ~id_side,
                                           "id",                                    NA,                      NA,       NA,       NA,
                       "funding_project_number",                                    NA,                      NA,       NA,       NA,
                              "funding_project",                                    NA,                      NA,       NA,       NA,
                                   "project_id",                                    NA,                      NA,       NA,       NA,
                               "funding_source",                                    NA,                      NA,       NA,       NA,
                       "responsible_party_name",                                    NA,                      NA,       NA,       NA,
                              "consultant_name",                                    NA,                      NA,       NA,       NA,
                              "assessment_date",                                "date",                  "Date",       1L,       1L,
                           "stream_crossing_id",                   "pscis_crossing_id",              "PSCIS ID",       2L,       1L,
                                "assessment_id",                                    NA,                      NA,       NA,       NA,
                  "external_crossing_reference",               "my_crossing_reference",           "External ID",       3L,       1L,
                                 "crew_members",                        "crew_members",                  "Crew",       5L,       1L,
                                     "utm_zone",                            "utm_zone",              "UTM Zone",       6L,       1L,
                                  "utm_easting",                             "easting",               "Easting",       7L,       1L,
                                 "utm_northing",                            "northing",              "Northing",       8L,       1L,
                      "location_confidence_ind",                                    NA,                      NA,       NA,       NA,
                                  "stream_name",                         "stream_name",                "Stream",       9L,       1L,
                                    "road_name",                           "road_name",                  "Road",      10L,       1L,
                                 "road_km_mark",                        "road_km_mark",                      NA,       NA,       NA,
                                  "road_tenure",                         "road_tenure",           "Road Tenure",      11L,       1L,
                           "crossing_type_code",                       "crossing_type",         "Crossing Type",       NA,       NA,
                           "crossing_type_desc",                                    NA,                      NA,       NA,       NA,
                        "crossing_subtype_code",                    "crossing_subtype",     "Crossing Sub Type",       1L,       2L,
                        "crossing_subtype_desc",                                    NA,                      NA,       NA,       NA,
                             "diameter_or_span",             "diameter_or_span_meters",          "Diameter (m)",       2L,       2L,
                              "length_or_width",              "length_or_width_meters",            "Length (m)",       3L,       2L,
                  "continuous_embeddedment_ind",      "continuous_embeddedment_yes_no",              "Embedded",       5L,       2L,
                   "average_depth_embededdment",   "average_depth_embededdment_meters",    "Depth Embedded (m)",       6L,       2L,
                         "resemble_channel_ind",             "resemble_channel_yes_no",      "Resemble Channel",       7L,       2L,
                              "backwatered_ind",                  "backwatered_yes_no",           "Backwatered",       8L,       2L,
                       "percentage_backwatered",              "percentage_backwatered",   "Percent Backwatered",       9L,       2L,
                                   "fill_depth",                   "fill_depth_meters",        "Fill Depth (m)",      10L,       2L,
                                  "outlet_drop",                  "outlet_drop_meters",       "Outlet Drop (m)",      11L,       2L,
                            "outlet_pool_depth",             "outlet_pool_depth_0_01m", "Outlet Pool Depth (m)",      12L,       2L,
                               "inlet_drop_ind",                   "inlet_drop_yes_no",            "Inlet Drop",      13L,       2L,
                                "culvert_slope",               "culvert_slope_percent",             "Slope (%)",      14L,       2L,
                     "downstream_channel_width",     "downstream_channel_width_meters",     "Channel Width (m)",      12L,       1L,
                                 "stream_slope",                        "stream_slope",      "Stream Slope (%)",      13L,       1L,
                          "beaver_activity_ind",              "beaver_activity_yes_no",       "Beaver Activity",      14L,       1L,
                            "fish_observed_ind",                "fish_observed_yes_no",          "Fish Sighted",       NA,       NA,
                             "valley_fill_code",                         "valley_fill",           "Valley Fill",      15L,       2L,
                        "valley_fill_code_desc",                                    NA,                      NA,       NA,       NA,
                           "habitat_value_code",                       "habitat_value",         "Habitat Value",      15L,       1L,
                           "habitat_value_desc",                                    NA,                      NA,       NA,       NA,
                           "stream_width_ratio",                  "stream_width_ratio",                   "SWR",       NA,       NA,
                     "stream_width_ratio_score",                                    NA,                 "Score",       NA,       NA,
                         "culvert_length_score",                "culvert_length_score",                 "Score",       NA,       NA,
                                  "embed_score",                         "embed_score",                 "Score",       NA,       NA,
                            "outlet_drop_score",                   "outlet_drop_score",                 "Score",       NA,       NA,
                          "culvert_slope_score",                 "culvert_slope_score",                 "Score",       NA,       NA,
                                  "final_score",                         "final_score",           "Final score",      16L,       1L,
                          "barrier_result_code",                      "barrier_result",        "Barrier Result",      16L,       2L,
                   "barrier_result_description",                                    NA,                      NA,       NA,       NA,
                            "crossing_fix_code",                                    NA,                      NA,       NA,       NA,
                            "crossing_fix_desc",                        "crossing_fix",              "Fix type",      17L,       1L,
                 "recommended_diameter_or_span", "recommended_diameter_or_span_meters",   "Fix Span / Diameter",      17L,       2L,
                           "assessment_comment",                  "assessment_comment",               "Comment",       NA,       NA,
                                   "ecocat_url",                                    NA,                      NA,       NA,       NA,
                               "image_view_url",                                    NA,                      NA,       NA,       NA,
                         "current_pscis_status",                                    NA,                      NA,       NA,       NA,
                   "current_crossing_type_code",                                    NA,                      NA,       NA,       NA,
                   "current_crossing_type_desc",                                    NA,                      NA,       NA,       NA,
                "current_crossing_subtype_code",                                    NA,                      NA,       NA,       NA,
                "current_crossing_subtype_desc",                                    NA,                      NA,       NA,       NA,
                  "current_barrier_result_code",                                    NA,                      NA,       NA,       NA,
                  "current_barrier_description",                                    NA,                      NA,       NA,       NA,
                                 "feature_code",                                    NA,                      NA,       NA,       NA,
                                     "objectid",                                    NA,                      NA,       NA,       NA,
                             "se_anno_cad_data",                                    NA,                      NA,       NA,       NA,
                                     "geometry",                                    NA,                      NA,       NA,       NA
                )

usethis::use_data(xref_names_pscis, overwrite = TRUE)
