# Generated by staticimports; do not edit by hand.
# ======================================================================
# Imported from pkg:staticimports
# ======================================================================

# this is necessary to get around R's weird rounding where 1.55 would round to 1.5 vs 1.6 as we would expect.
sngu_round <- function(x, decimal_places = 1) {
  multiplier <- 10^decimal_places
  floor(x * multiplier + 0.5) / multiplier
}
